app:
  # 是否启用ansi控制台输出有颜色的字体
  enable-ansi: true
server:
  port: 8812
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kjps?useUnicode=true&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
